name: cs595
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pip
  - matplotlib
  - ipykernel  # for jupyter notebook support
  - scikit-learn
  - seaborn
  - pip:
    - ./local_modules/scallopy-0.2.4-cp310-cp310-manylinux_2_27_x86_64.whl
    - ./local_modules/scallop-0.2.4-py3-none-any.whl
    - ./local_modules/scallopy_ext-0.2.4-py3-none-any.whl
    - opencv-python-headless